version: "3"

services:
  database:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "mural-digital"
    ports:
      - "3306:3306"
    volumes:
      - .:/usr/database
    cap_add:
      - SYS_NICE
    restart: always

  server:
    container_name: server
    image: server
    depends_on:
      - database
    build: .
    command: yarn start
    ports: 
      - "3001:3001"
    volumes:
      - .:/usr/app
    restart: always
